-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  description text,
  rating INTEGER DEFAULT 1
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('Thinkful', 'https://www.thinkful.com', 'The Thinkful website', '5'),
  ('Netflix', 'https://www.netflix.com', 'Where you can watch movies', '5'),
  ('Nordstrom Rack', 'https://www.nordstromrack.com', 'Nordstrom stuff cheaper', '5'),
  ('Spotify', 'https://www.spotify.com', 'Music player', '3'),
  ('LinkedIn', 'https://www.linkedin.com', 'Linkedin site', '2'),
  ('Google', 'https://www.google.com', 'search on google', null),
  ('Hulu', 'https://www.hulu.com', 'another place to watch movies and shows', '5'),
  ('Facebook', 'https://www.facebook.com', 'social network', '5'),
  ('Sephora', 'https://www.sephora.com', 'Shop for makeup', '4'),
  ('YouTube', 'https://www.youtube.com', 'watch videos', '4');